apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow-app
  namespace: dev
  labels:
    app: yellow-app
spec:
  selector:
    matchLabels:
      app: yellow-app
  replicas: 1
  template:
    metadata:
      labels:
        app: yellow-app
    spec:
      containers:
      - name: yellow
        image: 331879450537.dkr.ecr.us-west-2.amazonaws.com/yellow:latest
        ports:
            - containerPort: 80
        resources:
          limits:
            memory: "1000Mi"
            cpu: "250m"
          requests:
            memory: "1000Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: yellow-service
  labels:
    app: yellow-app
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /yellow/index.html
spec:
  type: NodePort
  selector:
    app: yellow-app
  ports:
    - port: 80
      targetPort: 80